/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee_shop_java.project;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class BranchForm extends javax.swing.JFrame {

    public BranchForm() {
        initComponents();
        showBranches();
        setCbCompany();
        setRowIdWidth();
        btnUpdate.setEnabled(false);
    }
    PreparedStatement stmt = null;
    ResultSet rs; 
    
    public void setCbCompany(){
        String sql = "SELECT * FROM companies";
        try {
            stmt = DbConn.getConnection().prepareStatement(sql);
            rs = stmt.executeQuery();
            int i = 0;
            while(rs.next()) {
                cbCompanies.addItem(rs.getString("name"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
    }
    
    public ArrayList<Branch> getAllBranches(){
        ArrayList<Branch> branchList = new ArrayList<>();
        String sqlGetBranch = "SELECT branches.*, companies.name AS company_name FROM `branches` INNER JOIN companies ON branches.company_id = companies.id";
        try {
            stmt = DbConn.getConnection().prepareStatement(sqlGetBranch);
            rs = stmt.executeQuery();
            Branch branch;
            int i = 0;
            while(rs.next()){
                i++;
                branch = new Branch (i, rs.getString("name"), rs.getString("phone"), rs.getString("email"), rs.getString("address"), rs.getString("company_name"), rs.getInt("id"));
                branchList.add(branch);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return branchList;
    }
    
    public void showBranches(){
        tblBranches.setModel(new DefaultTableModel(null, new String[]{"ID", "Name", "Phone", "Email", "Address", "Company", "id"}));
        ArrayList<Branch> listBranches = getAllBranches();
        DefaultTableModel model = (DefaultTableModel) tblBranches.getModel();
        Object[] rows = new Object[7];
        for(int i=0; i<listBranches.size(); i++){
            rows[0] = listBranches.get(i).getTblId();
            rows[1] = listBranches.get(i).getName();
            rows[2] = listBranches.get(i).getEmail();
            rows[3] = listBranches.get(i).getPhone();
            rows[4] = listBranches.get(i).getAddress();
            rows[5] = listBranches.get(i).getCompanyName();
            rows[6] = listBranches.get(i).getId();
            model.addRow(rows);
        }
        setRowIdWidth();
    }
    
    public void setRowIdWidth(){
        DefaultTableColumnModel columnModel = (DefaultTableColumnModel) tblBranches.getColumnModel();
        columnModel.getColumn(6).setWidth(0);
        columnModel.getColumn(6).setPreferredWidth(0);
        columnModel.getColumn(6).setMinWidth(0);
        columnModel.getColumn(6).setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelbranches = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBranches = new javax.swing.JTable();
        jpanel2 = new javax.swing.JPanel();
        jLabelregisterbranches = new javax.swing.JLabel();
        jLabelbname = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelbphonenumber = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelbemail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabelbaddress = new javax.swing.JLabel();
        cbCompanies = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 204));

        jLabelbranches.setBackground(new java.awt.Color(255, 255, 255));
        jLabelbranches.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabelbranches.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbranches.setText("Branches...");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/client_company_110px.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        tblBranches.setAutoCreateRowSorter(true);
        tblBranches.setBackground(new java.awt.Color(153, 153, 255));
        tblBranches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Phone", "Email", "Address", "Company", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBranches.setInheritsPopupMenu(true);
        tblBranches.setSelectionForeground(new java.awt.Color(153, 153, 255));
        tblBranches.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBranches.setShowGrid(true);
        tblBranches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBranchesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBranches);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelbranches))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelbranches)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 491));

        jpanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabelregisterbranches.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelregisterbranches.setForeground(new java.awt.Color(255, 255, 255));
        jLabelregisterbranches.setText("Register Branches");

        jLabelbname.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabelbname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbname.setText("Branch Name :");

        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("Name");
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jSeparator2.setMaximumSize(new java.awt.Dimension(33767, 33767));

        jLabelbphonenumber.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabelbphonenumber.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbphonenumber.setText("Phone Number :");

        txtPhone.setBackground(new java.awt.Color(51, 51, 51));
        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setText("Phone");
        txtPhone.setBorder(null);
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        jSeparator4.setMaximumSize(new java.awt.Dimension(33767, 33767));

        jLabelbemail.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabelbemail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbemail.setText("Email :");

        txtEmail.setBackground(new java.awt.Color(51, 51, 51));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jSeparator5.setMaximumSize(new java.awt.Dimension(33767, 33767));

        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setText("Address");
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(txtAddress);

        jLabelbaddress.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabelbaddress.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbaddress.setText("Address :");

        cbCompanies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCompaniesItemStateChanged(evt);
            }
        });
        cbCompanies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompaniesActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 25));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel2Layout = new javax.swing.GroupLayout(jpanel2);
        jpanel2.setLayout(jpanel2Layout);
        jpanel2Layout.setHorizontalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabelregisterbranches)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpanel2Layout.createSequentialGroup()
                            .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelbname)
                                .addComponent(jLabelbphonenumber)
                                .addComponent(jLabelbemail)
                                .addComponent(jLabelbaddress))
                            .addGap(22, 22, 22)
                            .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmail)
                                .addComponent(txtPhone)
                                .addComponent(txtName)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jpanel2Layout.setVerticalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelregisterbranches)
                .addGap(26, 26, 26)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelbname)
                            .addGroup(jpanel2Layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelbphonenumber)
                            .addGroup(jpanel2Layout.createSequentialGroup()
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelbemail))
                .addGap(18, 18, 18)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelbaddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );

        btnAdd.setBackground(new Color(255, 255, 255));

        getContentPane().add(jpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 390, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Branch myBranch = new Branch();
    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        if(txtName.getText().toLowerCase().equals("name")) {
            txtName.setText("");
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        if(txtName.getText().toLowerCase().equals("")) {
            txtName.setText("Name");
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        // TODO add your handling code here:
        if(txtPhone.getText().toLowerCase().equals("phone")) {
            txtPhone.setText("");
        }
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        // TODO add your handling code here:
        if(txtPhone.getText().toLowerCase().equals("")) {
            txtPhone.setText("Phone");
        }
    }//GEN-LAST:event_txtPhoneFocusLost

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if(txtEmail.getText().toLowerCase().equals("email")) {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if(txtEmail.getText().toLowerCase().equals("")) {
            txtEmail.setText("Email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        // TODO add your handling code here:
        if(txtAddress.getText().toLowerCase().equals("address")) {
            txtAddress.setText("");
        }
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        // TODO add your handling code here:
        if(txtAddress.getText().toLowerCase().equals("")) {
            txtAddress.setText("Address");
        }
    }//GEN-LAST:event_txtAddressFocusLost

    private void cbCompaniesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCompaniesItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCompaniesItemStateChanged

    private void cbCompaniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompaniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCompaniesActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String email = txtEmail.getText().trim();
        String address = txtAddress.getText().trim();
        if(name.equals("") || phone.equals("") || email.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out the required fields");
        } else{
            String sqlGetId = "SELECT id FROM companies WHERE LOWER(name) = ?";
            try {
                stmt= DbConn.getConnection().prepareStatement(sqlGetId);
                stmt.setString(1, String.valueOf(cbCompanies.getSelectedItem()));
                rs = stmt.executeQuery();
                if(rs.next()){
                    myBranch.setCompanyId(rs.getInt("id"));
                } else{
                    JOptionPane.showMessageDialog(null, "Company ID not Found");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            myBranch.setName(name);
            myBranch.setEmail(email);
            myBranch.setPhone(phone);
            myBranch.setAddress(address);
            myBranch.insert();
            showBranches();
            txtName.setText("Name");
            txtPhone.setText("Phone");
            txtEmail.setText("Email");
            txtAddress.setText("Address");
            cbCompanies.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int id = (int) tblBranches.getValueAt(tblBranches.getSelectedRow(), 6);
        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String email = txtEmail.getText().trim();
        String address = txtAddress.getText().trim();
        if(name.equals("") || phone.equals("") || email.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out the required fields");
        }
        String sqlGetId = "SELECT id FROM companies WHERE LOWER(name) = ?";
        try {
            stmt= DbConn.getConnection().prepareStatement(sqlGetId);
            stmt.setString(1, String.valueOf(cbCompanies.getSelectedItem()));
            rs = stmt.executeQuery();
            if(rs.next()){
                myBranch.setCompanyId(rs.getInt("id"));
            } else{
                JOptionPane.showMessageDialog(null, "Company ID not Found");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
//        int i = tblBranches.getSelectedRow();
//        DefaultTableModel model = (DefaultTableModel)tblBranches.getModel();
//        id = (int) model.getValueAt(6, NORMAL);
//        model.setValueAt(txtName.getText(), i, 1);
//        model.setValueAt(txtPhone.getText(), i, 2);
//        model.setValueAt(txtEmail.getText(), i, 3);
//        model.setValueAt(txtAddress.getText(), i, 4);
//        model.setValueAt(cbCompanies.getSelectedItem(), i, 5);

//        if(btnUpdate.getText().toLowerCase().equals("update")){
//            btnUpdate.setText("Edit");
//            btnAdd.setEnabled(false);
//            tblBranches.setEnabled(false);
//            if(i >= 0)
//            {
//
//            } else {
//               JOptionPane.showMessageDialog(null, "Error");
//            }
//        } else if(btnUpdate.getText().toLowerCase().equals("edit")){
//            btnUpdate.setText("Update");
//            btnAdd.setEnabled(true);
//            tblBranches.setEnabled(true);
//        }
        System.out.print(id);
        myBranch.setName(name);
        myBranch.setEmail(email);
        myBranch.setPhone(phone);
        myBranch.setAddress(address);
        myBranch.update(id);
        showBranches();
        txtName.setText("Name");
        txtPhone.setText("Phone");
        txtEmail.setText("Email");
        txtAddress.setText("Address");
        cbCompanies.setSelectedIndex(0);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void tblBranchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBranchesMouseClicked
        // TODO add your handling code here:
        int row = tblBranches.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblBranches.getModel();
        txtName.setText(model.getValueAt( row, 1).toString());
        txtPhone.setText(model.getValueAt( row, 2).toString());
        txtEmail.setText(model.getValueAt( row, 3).toString());
        txtAddress.setText(model.getValueAt( row, 4).toString());
        cbCompanies.setSelectedItem(model.getValueAt( row, 5).toString());
        System.out.println(row);
        if(row >= 0){
            btnUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_tblBranchesMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int id = (int) tblBranches.getValueAt(tblBranches.getSelectedRow(), 6);
        myBranch.delete(id);
        showBranches();
        txtName.setText("Name");
        txtPhone.setText("Phone");
        txtEmail.setText("Email");
        txtAddress.setText("Address");
        cbCompanies.setSelectedIndex(0);
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BranchForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbCompanies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelbaddress;
    private javax.swing.JLabel jLabelbemail;
    private javax.swing.JLabel jLabelbname;
    private javax.swing.JLabel jLabelbphonenumber;
    private javax.swing.JLabel jLabelbranches;
    private javax.swing.JLabel jLabelregisterbranches;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel jpanel2;
    private javax.swing.JTable tblBranches;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private Object btnUpdate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
