/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package coffee_shop_java.project;

import java.awt.Color;

/**
 *
 * @author LYOKO
 */
public class MainMenu extends javax.swing.JFrame {

    /** Creates new form MainMenu */
    public MainMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        company = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        branch = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        products = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        stock = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        additional = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        topbar = new javax.swing.JPanel();
        dynamicpanel = new javax.swing.JLayeredPane();
        companycard = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        branchcard = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        productscard = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        stockcard = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        usercard = new javax.swing.JPanel();
        userpanel = new javax.swing.JLayeredPane();
        userShow = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userAdd = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        userEdit = new javax.swing.JPanel();
        userDelete = new javax.swing.JPanel();
        showall = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        addnew = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        additionalcard = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel5.setBackground(new java.awt.Color(51, 255, 51));

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 514, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 445, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(22, 61, 141));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        company.setBackground(new java.awt.Color(22, 46, 126));
        company.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyFocusGained(evt);
            }
        });
        company.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                companyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                companyMouseExited(evt);
            }
        });
        company.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("COMPANY");
        company.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/icons8_organization_50px.png"))); // NOI18N
        company.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        sidebar.add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 70));

        branch.setBackground(new java.awt.Color(22, 46, 126));
        branch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                branchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                branchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                branchMouseExited(evt);
            }
        });
        branch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BRANCH");
        branch.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/icons8_company_50px_1.png"))); // NOI18N
        branch.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        sidebar.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 70));

        products.setBackground(new java.awt.Color(22, 46, 126));
        products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productsMouseExited(evt);
            }
        });
        products.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PRODUCTS");
        products.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/icons8_coffee_50px.png"))); // NOI18N
        products.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        sidebar.add(products, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 70));

        stock.setBackground(new java.awt.Color(22, 46, 126));
        stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockMouseExited(evt);
            }
        });
        stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("STOCK");
        stock.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/icons8_box_50px.png"))); // NOI18N
        stock.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 50));

        sidebar.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 70));

        user.setBackground(new java.awt.Color(22, 46, 126));
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userMouseExited(evt);
            }
        });
        user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USER");
        user.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/icons8_user_filled_50px.png"))); // NOI18N
        user.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        sidebar.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 70));

        additional.setBackground(new java.awt.Color(22, 46, 126));
        additional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                additionalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                additionalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                additionalMouseExited(evt);
            }
        });
        additional.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/icons8_coming_soon_50px.png"))); // NOI18N
        additional.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("COMING SOON");
        additional.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        sidebar.add(additional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 220, 70));

        logout.setBackground(new java.awt.Color(22, 46, 126));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/icons8_logout_rounded_left_50px.png"))); // NOI18N
        logout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOG OUT");
        logout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        sidebar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 220, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("THE BEAN");
        sidebar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 160, 50));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_shop_java/icons/icons8_java_coffee_bean_logo_50px.png"))); // NOI18N
        sidebar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        background.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -1, 220, 690));

        topbar.setBackground(java.awt.Color.lightGray);

        org.jdesktop.layout.GroupLayout topbarLayout = new org.jdesktop.layout.GroupLayout(topbar);
        topbar.setLayout(topbarLayout);
        topbarLayout.setHorizontalGroup(
            topbarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 840, Short.MAX_VALUE)
        );
        topbarLayout.setVerticalGroup(
            topbarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );

        background.add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 840, 50));

        dynamicpanel.setLayout(new java.awt.CardLayout());

        companycard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("COMPANY");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOG OUT");

        org.jdesktop.layout.GroupLayout companycardLayout = new org.jdesktop.layout.GroupLayout(companycard);
        companycard.setLayout(companycardLayout);
        companycardLayout.setHorizontalGroup(
            companycardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(companycardLayout.createSequentialGroup()
                .add(companycardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(companycardLayout.createSequentialGroup()
                        .add(369, 369, 369)
                        .add(jLabel18))
                    .add(companycardLayout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jLabel3)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        companycardLayout.setVerticalGroup(
            companycardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(companycardLayout.createSequentialGroup()
                .add(312, 312, 312)
                .add(jLabel18)
                .add(18, 18, 18)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        dynamicpanel.add(companycard, "card2");

        branchcard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("BRANCH");

        org.jdesktop.layout.GroupLayout branchcardLayout = new org.jdesktop.layout.GroupLayout(branchcard);
        branchcard.setLayout(branchcardLayout);
        branchcardLayout.setHorizontalGroup(
            branchcardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(branchcardLayout.createSequentialGroup()
                .add(343, 343, 343)
                .add(jLabel17)
                .addContainerGap(456, Short.MAX_VALUE))
        );
        branchcardLayout.setVerticalGroup(
            branchcardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(branchcardLayout.createSequentialGroup()
                .add(287, 287, 287)
                .add(jLabel17)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        dynamicpanel.add(branchcard, "card2");

        productscard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setText("PRODUCTS");

        org.jdesktop.layout.GroupLayout productscardLayout = new org.jdesktop.layout.GroupLayout(productscard);
        productscard.setLayout(productscardLayout);
        productscardLayout.setHorizontalGroup(
            productscardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(productscardLayout.createSequentialGroup()
                .add(382, 382, 382)
                .add(jLabel19)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        productscardLayout.setVerticalGroup(
            productscardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(productscardLayout.createSequentialGroup()
                .add(295, 295, 295)
                .add(jLabel19)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        dynamicpanel.add(productscard, "card2");

        stockcard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setText("STOCK");

        org.jdesktop.layout.GroupLayout stockcardLayout = new org.jdesktop.layout.GroupLayout(stockcard);
        stockcard.setLayout(stockcardLayout);
        stockcardLayout.setHorizontalGroup(
            stockcardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stockcardLayout.createSequentialGroup()
                .add(378, 378, 378)
                .add(jLabel20)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        stockcardLayout.setVerticalGroup(
            stockcardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stockcardLayout.createSequentialGroup()
                .add(291, 291, 291)
                .add(jLabel20)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        dynamicpanel.add(stockcard, "card2");

        usercard.setBackground(new java.awt.Color(51, 153, 0));
        usercard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userpanel.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Position", "Salary", "Worktime", "CV", "Company_ID", "Branch_ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout userShowLayout = new org.jdesktop.layout.GroupLayout(userShow);
        userShow.setLayout(userShowLayout);
        userShowLayout.setHorizontalGroup(
            userShowLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        userShowLayout.setVerticalGroup(
            userShowLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        userpanel.add(userShow, "card2");

        jButton1.setText("Summit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout userAddLayout = new org.jdesktop.layout.GroupLayout(userAdd);
        userAdd.setLayout(userAddLayout);
        userAddLayout.setHorizontalGroup(
            userAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, userAddLayout.createSequentialGroup()
                .addContainerGap(754, Short.MAX_VALUE)
                .add(jButton1)
                .add(19, 19, 19))
        );
        userAddLayout.setVerticalGroup(
            userAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, userAddLayout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
        );

        userpanel.add(userAdd, "card2");

        org.jdesktop.layout.GroupLayout userEditLayout = new org.jdesktop.layout.GroupLayout(userEdit);
        userEdit.setLayout(userEditLayout);
        userEditLayout.setHorizontalGroup(
            userEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 840, Short.MAX_VALUE)
        );
        userEditLayout.setVerticalGroup(
            userEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 570, Short.MAX_VALUE)
        );

        userpanel.add(userEdit, "card2");

        userDelete.setBackground(new java.awt.Color(0, 204, 0));

        org.jdesktop.layout.GroupLayout userDeleteLayout = new org.jdesktop.layout.GroupLayout(userDelete);
        userDelete.setLayout(userDeleteLayout);
        userDeleteLayout.setHorizontalGroup(
            userDeleteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 840, Short.MAX_VALUE)
        );
        userDeleteLayout.setVerticalGroup(
            userDeleteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 570, Short.MAX_VALUE)
        );

        userpanel.add(userDelete, "card2");

        usercard.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        showall.setBackground(new java.awt.Color(51, 204, 0));
        showall.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showallMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Show All");

        org.jdesktop.layout.GroupLayout showallLayout = new org.jdesktop.layout.GroupLayout(showall);
        showall.setLayout(showallLayout);
        showallLayout.setHorizontalGroup(
            showallLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(showallLayout.createSequentialGroup()
                .add(62, 62, 62)
                .add(jLabel21)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        showallLayout.setVerticalGroup(
            showallLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, showallLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .add(jLabel21)
                .add(22, 22, 22))
        );

        usercard.add(showall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 574, 190, 70));

        addnew.setBackground(new java.awt.Color(51, 204, 0));
        addnew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addnewMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Add New");

        org.jdesktop.layout.GroupLayout addnewLayout = new org.jdesktop.layout.GroupLayout(addnew);
        addnew.setLayout(addnewLayout);
        addnewLayout.setHorizontalGroup(
            addnewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, addnewLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .add(jLabel25)
                .add(78, 78, 78))
        );
        addnewLayout.setVerticalGroup(
            addnewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addnewLayout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jLabel25)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        usercard.add(addnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 574, 220, 70));

        edit.setBackground(new java.awt.Color(51, 204, 0));
        edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Edit");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Add New");

        org.jdesktop.layout.GroupLayout editLayout = new org.jdesktop.layout.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(editLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .add(editLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, editLayout.createSequentialGroup()
                        .add(jLabel27)
                        .add(65, 65, 65))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, editLayout.createSequentialGroup()
                        .add(jLabel26)
                        .add(83, 83, 83))))
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(editLayout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel26)
                .add(27, 27, 27)
                .add(jLabel27)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usercard.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 574, 200, 70));

        delete.setBackground(new java.awt.Color(0, 204, 0));
        delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Delete");
        delete.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        usercard.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 574, 230, 70));

        dynamicpanel.add(usercard, "card2");

        additionalcard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("COMING SOON");

        org.jdesktop.layout.GroupLayout additionalcardLayout = new org.jdesktop.layout.GroupLayout(additionalcard);
        additionalcard.setLayout(additionalcardLayout);
        additionalcardLayout.setHorizontalGroup(
            additionalcardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(additionalcardLayout.createSequentialGroup()
                .add(370, 370, 370)
                .add(jLabel22)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        additionalcardLayout.setVerticalGroup(
            additionalcardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(additionalcardLayout.createSequentialGroup()
                .add(295, 295, 295)
                .add(jLabel22)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        dynamicpanel.add(additionalcard, "card2");

        background.add(dynamicpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 840, 640));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyMouseClicked
        // TODO add your handling code here:
       
       dynamicpanel.removeAll();
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
       
       dynamicpanel.add(companycard);
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
       
    }//GEN-LAST:event_companyMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
       dynamicpanel.removeAll();
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
        
    }//GEN-LAST:event_formWindowOpened

    private void companyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyMouseEntered
        // TODO add your handling code here:
         company.setBackground(new Color(46, 49, 49));
    }//GEN-LAST:event_companyMouseEntered

    private void companyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyFocusGained
        // TODO add your handling code here:
       //company.setBackground(new Color(22, 46, 126));
    }//GEN-LAST:event_companyFocusGained

    private void branchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchMouseClicked
        // TODO add your handling code here:
       dynamicpanel.removeAll();
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
       
       dynamicpanel.add(branchcard);
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
    }//GEN-LAST:event_branchMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseClicked
        // TODO add your handling code here:
       dynamicpanel.removeAll();
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
       
       dynamicpanel.add(productscard);
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
    }//GEN-LAST:event_productsMouseClicked

    private void stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMouseClicked
        // TODO add your handling code here:
       dynamicpanel.removeAll();
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
       
       dynamicpanel.add(stockcard);
       dynamicpanel.repaint();
       dynamicpanel.revalidate();
    }//GEN-LAST:event_stockMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        dynamicpanel.removeAll();
        dynamicpanel.repaint();
        dynamicpanel.revalidate();

        dynamicpanel.add(usercard);
        dynamicpanel.repaint();
        dynamicpanel.revalidate();
    }//GEN-LAST:event_userMouseClicked

    private void additionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionalMouseClicked
        // TODO add your handling code here:
        dynamicpanel.removeAll();
        dynamicpanel.repaint();
        dynamicpanel.revalidate();

        dynamicpanel.add(additionalcard);
        dynamicpanel.repaint();
        dynamicpanel.revalidate();
    }//GEN-LAST:event_additionalMouseClicked

    private void companyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyMouseExited
        // TODO add your handling code here:
        company.setBackground(new Color(22, 46, 126));
    }//GEN-LAST:event_companyMouseExited

    private void branchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchMouseEntered
        // TODO add your handling code here:
        branch.setBackground(new Color(46, 49, 49));
    }//GEN-LAST:event_branchMouseEntered

    private void branchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchMouseExited
        // TODO add your handling code here:
        branch.setBackground(new Color(22, 46, 126));
    }//GEN-LAST:event_branchMouseExited

    private void productsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseEntered
        // TODO add your handling code here:
        products.setBackground(new Color(46, 49, 49));
    }//GEN-LAST:event_productsMouseEntered

    private void productsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseExited
        // TODO add your handling code here:
        products.setBackground(new Color(22, 46, 126));
    }//GEN-LAST:event_productsMouseExited

    private void stockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMouseEntered
        // TODO add your handling code here:
        stock.setBackground(new Color(46, 49, 49));
    }//GEN-LAST:event_stockMouseEntered

    private void stockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMouseExited
        // TODO add your handling code here:
        stock.setBackground(new Color(22, 46, 126));
    }//GEN-LAST:event_stockMouseExited

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        // TODO add your handling code here:
        user.setBackground(new Color(46, 49, 49));
    }//GEN-LAST:event_userMouseEntered

    private void userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseExited
        // TODO add your handling code here:
        user.setBackground(new Color(22, 46, 126));
    }//GEN-LAST:event_userMouseExited

    private void additionalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionalMouseEntered
        // TODO add your handling code here:
        additional.setBackground(new Color(46, 49, 49));
    }//GEN-LAST:event_additionalMouseEntered

    private void additionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionalMouseExited
        // TODO add your handling code here:
        additional.setBackground(new Color(22, 46, 126));
    }//GEN-LAST:event_additionalMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(46, 49, 49));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(new Color(22, 46, 126));
    }//GEN-LAST:event_logoutMouseExited

    private void showallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showallMouseClicked
        // TODO add your handling code here:
       userpanel.removeAll();
       userpanel.repaint();
       userpanel.revalidate();
       
       userpanel.add(userShow);
       userpanel.repaint();
       userpanel.revalidate();
    }//GEN-LAST:event_showallMouseClicked

    private void addnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnewMouseClicked
        // TODO add your handling code here:
       userpanel.removeAll();
       userpanel.repaint();
       userpanel.revalidate();
       
       userpanel.add(userAdd);
       userpanel.repaint();
       userpanel.revalidate();
    }//GEN-LAST:event_addnewMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel additional;
    private javax.swing.JPanel additionalcard;
    private javax.swing.JPanel addnew;
    private javax.swing.JPanel background;
    private javax.swing.JPanel branch;
    private javax.swing.JPanel branchcard;
    private javax.swing.JPanel company;
    private javax.swing.JPanel companycard;
    private javax.swing.JPanel delete;
    private javax.swing.JLayeredPane dynamicpanel;
    private javax.swing.JPanel edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel products;
    private javax.swing.JPanel productscard;
    private javax.swing.JPanel showall;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel stock;
    private javax.swing.JPanel stockcard;
    private javax.swing.JPanel topbar;
    private javax.swing.JPanel user;
    private javax.swing.JPanel userAdd;
    private javax.swing.JPanel userDelete;
    private javax.swing.JPanel userEdit;
    private javax.swing.JPanel userShow;
    private javax.swing.JPanel usercard;
    private javax.swing.JLayeredPane userpanel;
    // End of variables declaration//GEN-END:variables

}
